# Copyright 2017 (c) Michael Thomas (malinka) <malinka@entropy-development.com>
# Distributed under the terms of the GNU Affero General Public License v3

apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: style
spec:
    template:
        metadata:
            labels:
                app: style
        spec:
            containers:
            - name: style
              image: aelmalinka/style
              ports:
              - containerPort: 8080
              env:
              - name: PORT
                value: 8080
              - name: STYLE_PATH
                valueFrom:
                    configMapKeyRef:
                        name: website-config
                        key: style.path
              - name: STYLE_DEFAULT
                valueFrom:
                    configMapKeyRef:
                        name: website-config
                        key: style.default
---
apiVersion: v1
kind: Service
metadata:
    name: style
    labels:
        app: style
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      protocol: TCP
      name: http-style
    selector:
        app: style
