# Copyright 2016 (c) Michael Thomas (malinka) <malinka@entropy-development.com>

runtime: nodejs
vm: true
service: style
threadsafe: true
resources:
    memory_gb: .1
automatic_scaling:
    min_num_instances: 1
